### PR TITLE
refactor: rewrite to a web UI

### PR DESCRIPTION
**Pull request by favna**
Very much WIP

TODO:

- [x] Vercel deploys
- [x] Make the site
- [ ] Have @vladfrangu setup auth with CF (TBD)
- [x] ~~Learn how to do both CF and Vercel (should be doable?? Sapphire uses CF too as DNS)~~

### CODE REVIEW

**Comment by imranbarbhuiya** [comment]
for the 4th point https://vercel.com/support/articles/using-cloudflare-with-vercel#without-proxy-(dns-only)
just add the `CNAME` with the value `cname.vercel-dns.com` and you might need to add a `TXT` with a verification code after u change the url in vercel.

**Comment by favna** [comment]
> for the 4th point [vercel.com/support/articles/using-cloudflare-with-vercel#without-proxy-(dns-only)](https://vercel.com/support/articles/using-cloudflare-with-vercel#without-proxy-(dns-only)) just add the `CNAME` with the value `cname.vercel-dns.com` and you might need to add a `TXT` with a verification code after u change the url in vercel.

Oh dw I just wrote that in a hurry. We have an A record at CF that goes to the Vercel IP address and Vercel then takes over other CNAMEs

**Comment by favna** [comment]
WOOPS LOL

**Comment by vladfrangu** [comment]
I've done Vercel through cloudflare for discord-api-types.dev sooo it's easy enough. Painful that you have to disable caching tho and add some http rules 😢

**Comment by favna** [comment]
Closing this because rather than doing this in React I'm rewriting it in Nuxt

**Pull request closed without merging**
